name: build

on:
  push:
    branches:
      - 'master'
      - '*.*.*'
      - 'renovate/**'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - branding: tf2pickup.pl

    - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/tf2pickup-org/${{ matrix.branding }}

    - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
            branding=${{ matrix.branding }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Print image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
